### ISSUE TITLE
Type Assert Error

### ISSUE THREAD

**Issue by Ron-Notebooks** [rcalxrc08/FinancialMonteCarlo.jl#7]
In Julia 1.8.5  trying to runkouProcess=KouProcess(σ::num1,λ::num2,ρ::num3,λ₊::num4,λ₋::num5) where {num1,num2,num3,num4,num5 <: Number}

ERROR: TypeError: in typeassert, expected Type, got a value  of type TypeVar 

Black Scholes example runs and Pkg.test runs fine. Greeks are all of type Float 64 and isa(greek,Number) returns true.

Great code. Help

**Comment by rcalxrc08** [comment]
Can you copy paste exactly the code you are trying to run?
